# Generated by Django 2.2.13 on 2020-06-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otl', '0003_auto_20200619_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='answer0',
            new_name='AnsQ1',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer1',
            new_name='AnsQ10',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer2',
            new_name='AnsQ2',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer3',
            new_name='AnsQ3',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer4',
            new_name='AnsQ4',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer5',
            new_name='AnsQ5',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer6',
            new_name='AnsQ6',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer7',
            new_name='AnsQ7',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer8',
            new_name='AnsQ8',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='answer9',
            new_name='AnsQ9',
        ),
    ]
