# Generated by Django 2.2.13 on 2020-06-23 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otl', '0004_auto_20200619_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='submitby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
